### ISSUE TITLE
📚 Add Docker Setup Guide

### ISSUE THREAD

**Issue by Lumina-Oz-Dev** [Lumina-Oz-Dev/matchmaking-as-a-service#1]
## Description
Create comprehensive Docker setup documentation with examples to make deployment easier for developers.

## Priority
High

## Labels
- documentation
- good-first-issue
- enhancement

## Tasks
- [ ] Add Dockerfile optimization guide
- [ ] Create docker-compose examples for development
- [ ] Add troubleshooting section for common Docker issues
- [ ] Include environment variable documentation
- [ ] Add production deployment examples

## Acceptance Criteria
- Complete Docker setup guide in README
- Working docker-compose.yml file
- Troubleshooting section with common issues
- Environment setup examples

## Estimated Time
2-3 hours

This is a great first issue for contributors wanting to improve infrastructure documentation!

**Comment by Rushikesh-purohit-0503** [comment]
# Docker Setup Guide for Matchmaking-as-a-Service

This guide will help you containerize, optimize, and deploy the project using Docker. It covers development and production setups, environment variables, troubleshooting, and best practices.

---

## 1. Dockerfile Optimization Guide

- **Use Multi-Stage Builds:**
  - Reduce image size by separating build and runtime stages.
- **Leverage `.dockerignore`:**
  - Exclude files/folders like `node_modules`, `logs`, `docs`, and local configs.
- **Install Only Production Dependencies:**
  - Use `npm ci --only=production` for production images.
- **Cache Dependencies:**
  - Copy `package.json` and `package-lock.json` first, run `npm ci`, then copy the rest of the code.
- **Minimize Layers:**
  - Combine commands where possible (e.g., `RUN npm ci && npm cache clean --force`).
- **Set Non-Root User:**
  - For security, use a non-root user in production.

**Example Optimized Dockerfile:**
```Dockerfile
# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
USER node
CMD ["node", "dist/index.js"]
```

---

## 2. Docker Compose Examples for Development

**docker-compose.dev.yml**
```yaml
version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
```

**Usage:**
```bash
docker-compose -f docker-compose.dev.yml up --build
```

---

## 3. Troubleshooting Common Docker Issues

- **Container Exits Immediately:**
  - Check logs: `docker logs <container>`
  - Ensure `CMD` or `ENTRYPOINT` is correct.
- **File Changes Not Reflected:**
  - Ensure volumes are mounted correctly in Compose.
- **Port Already in Use:**
  - Change the host port mapping in Compose.
- **Permission Issues:**
  - Use a non-root user and set correct file permissions.
- **Network Issues:**
  - Use Docker Compose service names for inter-container communication.

---

## 4. Environment Variable Documentation

| Variable      | Description                        | Example Value                |
|---------------|------------------------------------|------------------------------|
| NODE_ENV      | Node environment                   | development, production      |
| PORT          | App listening port                 | 3000                         |
| REDIS_URL     | Redis connection string            | redis://redis:6379           |
| DB_HOST       | Database host                      | db                           |
| DB_PORT       | Database port                      | 5432                         |
| DB_USER       | Database user                      | user                         |
| DB_PASS       | Database password                  | password                     |
| DB_NAME       | Database name                      | matchmaking                  |

> Add any additional variables used in your `src/config` files.

---

## 5. Production Deployment Examples

**docker-compose.prod.yml**
```yaml
version: '3.8'
services:
  app:
    build:
      context: .
      target: production
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
```

## 6. Reverse Proxy with Nginx (Production)

**This setup enables SSL termination, load balancing, and better security.**
```bash
server {
    listen 80;
    server_name your-domain.com;

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Build and Run:** 
```bash
docker-compose -f docker-compose.prod.yml up --build -d
```

---
